##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  项目启动端口  ###################
server.port: 8092

###################  spring配置  ###################
spring:
  profiles:
    active: dev
  thymeleaf:
    mode: HTML
    cache: false
  mvc:
    view:
      prefix: /templates

logging:
  level:
    org.springframework.web.servlet: ERROR

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG
  file: /Users/xiaomeichen/study/2023-study/springboot-study/springboot-bucket/logs/app.log

