##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  项目启动端口  ###################
server.port: 8092

###################  spring配置  ###################
spring:
  profiles:
    active: dev

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    root: INFO
    com.xncoding: DEBUG
  path: /Users/xiaomeichen/study/2023-study/springboot-study/logs/springboot-aop

